# Configure a named Cloudflare Tunnel. Create the tunnel in Cloudflare Zero Trust
# and download the credentials file to this directory, then set
# CREDENTIALS_FILE in .env to the filename below.

tunnel: ${CLOUDFLARE_TUNNEL_ID}
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: ${N8N_HOST}
    service: http://n8n-main:5678
    originRequest:
      httpHostHeader: ${N8N_HOST}
  - hostname: ${N8N_WEBHOOK_HOST}
    service: http://n8n-webhook:5678
    originRequest:
      httpHostHeader: ${N8N_WEBHOOK_HOST}
  - hostname: ${N8N_SCRAPE_HOST}
    service: http://n8n-scrape-main:5678
    originRequest:
      httpHostHeader: ${N8N_SCRAPE_HOST}
  - hostname: ${N8N_SCRAPE_WEBHOOK_HOST}
    service: http://n8n-scrape-webhook:5678
    originRequest:
      httpHostHeader: ${N8N_SCRAPE_WEBHOOK_HOST}
  - hostname: ${PERPLEXICA_HOST}
    service: http://perplexica:3000
    originRequest:
      httpHostHeader: ${PERPLEXICA_HOST}
  - service: http_status:404
